# -*- coding: utf-8 -*-
"""abstract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zScWUXwWTZBvCvw_UgcUhJDzxuk3PIAq
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

IPV_data = pd.read_excel('IPVData.xlsx')
IPV_data.head()

article_titles_df = pd.DataFrame(IPV_data['Title of the articles']).dropna().reset_index(drop=True)
print("New DataFrame with article titles and no nulls:")
print(article_titles_df.head())

article_titles_df.to_csv('article_titles.csv', index=False)
from google.colab import files
files.download('article_titles.csv')
print("DataFrame saved to article_titles.csv and available for download.")

keywords = [] # Remove keywords for OpenAlex search
keyword_string = ' '.join(keywords)

# Extract article titles from the 'Title of the articles' column of IPV_data
# Drop NaN values and convert to a list
article_titles = IPV_data['Title of the articles'].dropna().tolist()

search_queries = []

for title in article_titles:
    if isinstance(title, str):
        search_queries.append(f"{title} {keyword_string}")

# Remove any trailing whitespace if keyword_string is empty
search_queries = [query.strip() for query in search_queries]

print("Generated the following search queries:")
for i, query in enumerate(search_queries[:5]):
    print(f"Query {i+1}: {query}")

uploaded_compare = files.upload()
print("CSV file uploaded.")

"""**Reasoning**:
Now that the comparison CSV is uploaded, I need to load it into a pandas DataFrame to proceed with the comparison. I will use the `pd.read_csv` function, accessing the content of the uploaded file from the `uploaded_compare` dictionary.


"""

import io

# Get the name of the uploaded file
compare_filename = next(iter(uploaded_compare))

# Read the uploaded CSV file into a DataFrame
compare_df = pd.read_csv(io.BytesIO(uploaded_compare[compare_filename]))

print(f"Uploaded file '{compare_filename}' loaded into DataFrame. First 5 rows:")
print(compare_df.head())

compare_df = compare_df.rename(columns={'title': 'Title of the articles'})

print("Columns in compare_df after renaming:")
print(compare_df.columns)

from urllib.parse import quote_plus

article_titles_to_search = not_found_articles_df['Title of the articles'].tolist()

openalex_search_queries = []

for title in article_titles_to_search:
    encoded_title = quote_plus(title)
    openalex_search_queries.append(encoded_title)

print("First 5 generated OpenAlex search queries:")
for i, query in enumerate(openalex_search_queries[:5]):
    print(f"Query {i+1}: {query}")